mobnetic/BitcoinChecker

- DataModule/src/com/mobnetic/coinguardian/model/market/Ripio.java
- add bid rate for Ripio
- high value is wrong
> add bid rate for Ripio

- DataModule/src/com/mobnetic/coinguardian/config/MarketsConfig.java
- DataModule/src/com/mobnetic/coinguardian/model/currency/Currency.java
- DataModule/src/com/mobnetic/coinguardian/model/currency/VirtualCurrency.java
- DataModule/src/com/mobnetic/coinguardian/model/market/Bitreserve.java
New contribution for bitreserve.org
Checked working with DataModuleTester.
Please add for the main Android App.
> New exchanger: bitreserve.org

- DataModule/src/com/mobnetic/coinguardian/config/MarketsConfig.java
- DataModule/src/com/mobnetic/coinguardian/model/market/BitoEX.java
Add support for BitoEX (Taiwan).
Due to this exchanger did not provide last price, so I assume ask price as last price.
It's my first time using Github, hoping everything is fine.
And sorry for my poor English.
> New exchange BitoEX.

- DataModule/src/com/mobnetic/coinguardian/config/MarketsConfig.java
- DataModule/src/com/mobnetic/coinguardian/model/market/Coinbase.java
- DataModule/src/com/mobnetic/coinguardian/model/market/CoinbaseExchange.java
Updated the API links in the Coinbase market to v2, as well as uncommented EUR and GBP as these are now supported by v2 properly. I also found API links for Coinbase Exchange, so added it as a new market - and of course tested all these.
Kindly include this in the next release, good Sir, as I myself would love to use these tickers in your excellent app :)
> New currencies for Coinbase and Coinbase Exchange support

- DataModule/src/com/mobnetic/coinguardian/config/MarketsConfig.java
- DataModule/src/com/mobnetic/coinguardian/model/market/Livecoin.java
This commit resolves #202 and #213 adding support for [Livecoin](https://www.livecoin.net/)
> Add Livecoin exchange

- DataModule/src/com/mobnetic/coinguardian/config/MarketsConfig.java
- DataModule/src/com/mobnetic/coinguardian/model/market/Gemini.java
This resolves #205 adding [Gemini](https://gemini.com/) support, gemini doesn't return a single price so I had to take the average of the asking and bidding price.
> Add Gemini exchange

- DataModule/src/com/mobnetic/coinguardian/config/MarketsConfig.java
- DataModule/src/com/mobnetic/coinguardian/model/market/Coinapult.java
This will resolve #204 by adding support for [coinapult](https://coinapult.com/)
> Add Coinapult exchange

- DataModule/src/com/mobnetic/coinguardian/model/market/Coinbase.java
Hi @MaciejCiemiega,
My old pull-request #191 already included this, but I have rebased this onto the new state, as I thought having dynamic currency pairs would be better than having a small list of fixed ones like currently available.
> Fetch currency pairs from Coinbase V2 API.

- DataModule/src/com/mobnetic/coinguardian/model/market/Bitso.java
Adding new currency ETH in Bitso
> Adding new currency ETH in Bitso

- dataModule/src/main/java/com/mobnetic/coinguardian/config/MarketsConfig.java
- dataModule/src/main/java/com/mobnetic/coinguardian/model/market/ETHEXIndia.java
Added Indian Ethereum exchange: 'ETHEX India', with the Currency Pair: 'ETH/INR'.
> New Exchange: ETHEX India

- dataModule/src/main/java/com/mobnetic/coinguardian/model/market/CoinMateIO.java
Coinmate.IO currencies changed to CZK and EUR
> Updated Coinmate.IO currencies

- dataModule/src/main/java/com/mobnetic/coinguardian/config/MarketsConfig.java
- dataModule/src/main/java/com/mobnetic/coinguardian/model/market/ChileBit.java
- dataModule/src/main/java/com/mobnetic/coinguardian/model/market/GateCoin.java
- dataModule/src/main/java/com/mobnetic/coinguardian/model/market/Liqui.java
- dataModule/src/main/java/com/mobnetic/coinguardian/model/market/SurBitcoin.java
- dataModule/src/main/java/com/mobnetic/coinguardian/model/market/VBtc.java
Added Gatecoin.com and Liqui.io exchanges with dynamic currency pairs. 
Also added 3 exchanges operated by BlinkTrade.com - ChileBit, SurBitcoin and VBTC. 
This pull request along with #275 resolves issues #262, #279 and #165 and #274.
> New Exchanges: Gatecoin, Liqui, ChileBit, SurBitcoin and VBTC

- dataModule/src/main/java/com/mobnetic/coinguardian/model/market/QuadrigaCX.java
Added the following currency pairs to QuadrigaCX:
- BTC-USD
- ETH-CAD
> Add new currency pairs to QuadrigaCX

- README.md
- dataModule/README.md
- dataModuleTester/README.md
Also added autogenerated ToC via [doctoc](https://github.com/thlorenz/doctoc).
> Reorganize README for readability on GitHub

- dataModule/src/main/java/com/mobnetic/coinguardian/model/market/Bitfinex.java
Adding support for XMR/BTC and XMR/USD.
> Adding support for XMR to Bitfinex

- dataModule/src/main/java/com/mobnetic/coinguardian/model/market/ETHEXIndia.java
Updated ETHEXIndia API endpoint. Fixes #339.
> Updated ETHEXIndia API endpoint. Fixes #339.

- dataModule/src/main/java/com/mobnetic/coinguardian/model/market/Bitso.java
I added ripple to bitso, let me know if I need to add something else.
resolve #323
> add xrp currency

- dataModule/src/main/java/com/mobnetic/coinguardian/config/MarketsConfig.java
- dataModule/src/main/java/com/mobnetic/coinguardian/model/market/Bithumb.java
- dataModule/src/main/java/com/mobnetic/coinguardian/model/market/Coinone.java
- dataModule/src/main/java/com/mobnetic/coinguardian/model/market/Korbit.java
I just did some work to cover all 3 major Korean exchanges :)
- 2 another major Korean exchanges: Coinone, Bithumb
- ETH, ETC support to Korbit
Fixes: #312 #321
> Add support for Coinone, Korbit(ETH, ETC), Bithumb

- dataModule/src/main/java/com/mobnetic/coinguardian/model/market/Bitfinex.java
I have tested this on the BitcoinCheckerDataModuleTester and it's working wonderful. Awesome app btw!
> Add XRP Currency for Bitfinex

- dataModule/src/main/java/com/mobnetic/coinguardian/model/market/Coinsph.java
Added support for the coins.ph exchange
This is so that Issue  #356 Can be closed
> Added support for the coins.ph exchange

- dataModule/src/main/java/com/mobnetic/coinguardian/config/MarketsConfig.java
- dataModule/src/main/java/com/mobnetic/coinguardian/model/market/Bl3p.java
Adds market configuration for [BL3P](https://bl3p.eu/), an exchange based in the Netherlands.
> BL3P exchange

- dataModule/src/main/java/com/mobnetic/coinguardian/model/market/QuadrigaCX.java
> Add LTC/CAD to QuadrigaCX

- dataModule/src/main/java/com/mobnetic/coinguardian/model/currency/VirtualCurrency.java
- dataModule/src/main/java/com/mobnetic/coinguardian/model/market/Coinone.java
- dataModule/src/main/java/com/mobnetic/coinguardian/model/market/Korbit.java
Updated currencies for Coinone, and Korbit.
> New currencies were added - Coinone, Korbit (Solve #419)

- dataModule/src/main/java/com/mobnetic/coinguardian/config/MarketsConfig.java
- dataModule/src/main/java/com/mobnetic/coinguardian/model/market/CoinFloor.java
Coinfloor.co.uk support for all currently available currency pairs
> Coinfloor support

- dataModule/src/main/java/com/mobnetic/coinguardian/config/MarketsConfig.java
- dataModule/src/main/java/com/mobnetic/coinguardian/model/market/Paribu.java
Added Turkish BTC Exchange Paribu.
> Added Turkish BTC Exchange Paribu.

- dataModule/src/main/java/com/mobnetic/coinguardian/model/market/Bl3p.java
BL3p now also supports LTC. This commit should add that support to the app.
> Add LTC support to BL3p

- dataModule/src/main/java/com/mobnetic/coinguardian/model/market/Bit2c.java
Bit2C market fixed to their current APIs
> Updated pairs on Bit2c

- dataModule/src/main/java/com/mobnetic/coinguardian/config/MarketsConfig.java
- dataModule/src/main/java/com/mobnetic/coinguardian/model/market/BtcXIndia.java
- dataModule/src/main/java/com/mobnetic/coinguardian/model/market/Koinex.java
- dataModule/src/main/java/com/mobnetic/coinguardian/model/market/Unocoin.java
- Added the exchange Koinex.in
- Added Unocoin as a new Exchange (even though it is technically not an exchange). 
- BTCXIndia has switched from BTC to XRP (Ripple) as their virtual currency, updated that as well.
- Resolves issues: #427, #475, #483, #488 and #501
> New Exchanges: Unocoin & Koinex.in & Updated Currency: BTCXindia

- dataModule/src/main/java/com/mobnetic/coinguardian/model/market/Bitso.java
Adding Litecoin currency for bitso.com
> Bitso - Adding LTC currency

- dataModule/src/main/java/com/mobnetic/coinguardian/model/market/Huobi.java
Hi, some updates about Huobi exchange.
1. Update Huobi API url
2. Huobi fetching currency pairs directly from exchange
> Update Huobi exchange

- dataModule/src/main/java/com/mobnetic/coinguardian/config/MarketsConfig.java
- dataModule/src/main/java/com/mobnetic/coinguardian/model/market/Binance.java
Added the popular Binance exchange. The Binance API is not great since it does not separate the currency pairs (a problem brought up in #433). I worked around this by adding a list of base currencies that Binance supports and using those to break down the currency pairs into the format that BitcoinChecker can read. This is probably the best solution until Binance makes their API better.
> New exchange Binance

- dataModule/src/main/java/com/mobnetic/coinguardian/config/MarketsConfig.java
- dataModule/src/main/java/com/mobnetic/coinguardian/model/currency/VirtualCurrency.java
- dataModule/src/main/java/com/mobnetic/coinguardian/model/market/Kucoin.java
> Add kucoin exchange

- dataModule/src/main/java/com/mobnetic/coinguardian/config/MarketsConfig.java
- dataModule/src/main/java/com/mobnetic/coinguardian/model/market/BitcoinTrade.java
URL: https://bitcointrade.com.br.
Pairs added: BTC|ETH|LTC/BRL.
Closes #511
> Add BitcoinTrade exchange.

- dataModule/src/main/java/com/mobnetic/coinguardian/config/MarketsConfig.java
- dataModule/src/main/java/com/mobnetic/coinguardian/model/market/OmniTrade.java
URL: https://omnitrade.io/
API Docs: https://help.omnitrade.io/area-de-desenvolvedores/apis-como-integrar-seu-sistema
API version: 2
Pairs: BTC|LTC|BCH|BTG|ETH|DASH|DCR/BRL.
> Add OmniTrade exchange.

- dataModule/src/main/java/com/mobnetic/coinguardian/model/market/Bit2c.java
Upgrade the coin list to the latest supported coins. 
also checked on an emulator, and it looks good.
> feat(bit2c): add the ETH/NIS and ETC/NIS pairs

- dataModule/src/main/java/com/mobnetic/coinguardian/config/MarketsConfig.java
- dataModule/src/main/java/com/mobnetic/coinguardian/model/market/Coinome.java
- dataModule/src/main/java/com/mobnetic/coinguardian/model/market/Zebpay.java
Zebpay addition of 4 New Coins other than BTC  and api Link Updated. + ( #704 )
And indentation accidentally happened! 
https://support.zebpay.com/hc/en-us/articles/115004228609-Zebpay-APIs
BTC: https://www.zebapi.com/api/v1/market/ticker-new/btc/inr
BCH: https://www.zebapi.com/api/v1/market/ticker-new/bch/inr
LTC: https://www.zebapi.com/api/v1/market/ticker-new/ltc/inr
XRP: https://www.zebapi.com/api/v1/market/ticker-new/xrp/inr
ETH: https://www.zebapi.com/api/v1/market/ticker-new/eth/inr
> Zebpay addition of New Coins - and Link Updation.

- dataModule/src/main/java/com/mobnetic/coinguardian/config/MarketsConfig.java
- dataModule/src/main/java/com/mobnetic/coinguardian/model/market/Nocks.java
This adds support for the [Nocks exchange](https://www.nocks.com/trade).
> Add support for Nocks exchange
